version: '3.5'

networks:
    server-network:
        driver: bridge

volumes:
  mysql-vol:
    driver: local

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./public:/opt/app/public
      - ./etc/infrastructure/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./etc/infrastructure/nginx/fastcgi_params:/etc/nginx/fastcgi_params:ro
      - ./etc/infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./etc/infrastructure/nginx/ssl:/etc/ssl
    ports:
      - "80:80"
      - "443:443"
    networks:
      - server-network
    depends_on:
      - php
  php:
      build:
        context: .
        dockerfile: docker/php/Dockerfile
      volumes:
        - .:/opt/app:delegated
        - ./docker/php/entrypoint.sh:/entrypoint.sh
      networks:
        - server-network
      entrypoint:
        - /entrypoint.sh
      environment:
        # DEBUG
        - XDEBUG_REMOTE_HOST=${XDEBUG_REMOTE_HOST}
      env_file:
        - .env
      depends_on:
        - mysql
  mysql:
      image: mysql:5.7.22
      restart: unless-stopped
      ports:
        - "3306:3306"
      networks:
          - server-network
      volumes:
        - ./etc/infrastructure/mysql:/etc/mysql
        - mysql-vol:/var/lib/mysql
      env_file:
        - .env
